### ISSUE TITLE
As a user I'd like to add a monthly expense so I can track and report my expenses 

### ISSUE THREAD

**Issue by SChurch89** [SChurch89/FerrisSE-Group1-Ewallet-SENG210#1]
3 pts

**Comment by SChurch89** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user I'd like to add a monthly expense so I can track and report my expenses](https://trello.com/c/YUCFoWYz/8-as-a-user-id-like-to-add-a-monthly-expense-so-i-can-track-and-report-my-expenses)

**Comment by acram002** [comment]
Possibly edit so title is class/method name and description includes user story
