### ISSUE TITLE
convertForeignCurrency

### ISSUE THREAD

**Issue by acram002** [SChurch89/FerrisSE-Group1-Ewallet-SENG210#11]
As a user I would like to view my current balance in a different currency [Bonus : try to use the same convert function to convert from foreign currency to USD]

**Comment by SChurch89** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [convertForeignCurrency: As a user I would like to view my current balance in a different currency [Bonus : try to use the same convert function to convert from foreign currency to USD]](https://trello.com/c/lxF6YFnY/8-convertforeigncurrency-as-a-user-i-would-like-to-view-my-current-balance-in-a-different-currency-bonus-try-to-use-the-same-conve)
