### ISSUE TITLE
As a user I'd like to add a monthly income so I can track and report my income all year 

### ISSUE THREAD

**Issue by SChurch89** [SChurch89/FerrisSE-Group1-Ewallet-SENG210#2]
3 points

**Comment by SChurch89** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user I'd like to add a monthly income so I can track and report my income all year](https://trello.com/c/RmNEUzNm/3-as-a-user-id-like-to-add-a-monthly-income-so-i-can-track-and-report-my-income-all-year)

**Comment by acram002** [comment]
Possibly edit so title is class/method name and description includes user story
