### ISSUE TITLE
As  a user I would like to view a detailed report of all expenses, income, and summary information  	

### ISSUE THREAD

**Issue by SChurch89** [SChurch89/FerrisSE-Group1-Ewallet-SENG210#3]

**Comment by SChurch89** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user I would like to view a detailed report of all expenses, income, and summary information](https://trello.com/c/PjdiVL4k/1-as-a-user-i-would-like-to-view-a-detailed-report-of-all-expenses-income-and-summary-information)

**Comment by acram002** [comment]
Possibly edit so title is class/method name and description includes user story
