### ISSUE TITLE
PrintExpenserReport

### ISSUE THREAD

**Issue by acram002** [SChurch89/FerrisSE-Group1-Ewallet-SENG210#6]
As a user I would like to view a detailed report of all expenses, and summary information for expenses

**Comment by SChurch89** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PrintExpenserReport: As a user I would like to view a detailed report of all expenses, and summary information for expenses](https://trello.com/c/WiPURnSh/3-printexpenserreport-as-a-user-i-would-like-to-view-a-detailed-report-of-all-expenses-and-summary-information-for-expenses)
