### ISSUE TITLE
PrintIncomeReport

### ISSUE THREAD

**Issue by acram002** [SChurch89/FerrisSE-Group1-Ewallet-SENG210#7]
As  a user I would like to view a detailed report of all income, and summary information for income

**Comment by SChurch89** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PrintIncomeReportByType: As  a user I would like to view a detailed report of income of a certain type, and summary information for income](https://trello.com/c/bPUkyOPm/5-printincomereportbytype-as-a-user-i-would-like-to-view-a-detailed-report-of-income-of-a-certain-type-and-summary-information-for)
