### ISSUE TITLE
PrintExpenseByType

### ISSUE THREAD

**Issue by acram002** [SChurch89/FerrisSE-Group1-Ewallet-SENG210#9]
As a user I would like to view a detailed report of expense of a certain type , and summary information for expenses

**Comment by SChurch89** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PrintExpenseByType: As a user I would like to view a detailed report of expense of a certain type , and summary information for expenses](https://trello.com/c/dlJvLKub/6-printexpensebytype-as-a-user-i-would-like-to-view-a-detailed-report-of-expense-of-a-certain-type-and-summary-information-for-exp)
